DATA:
    DATASET: 'cifar100'
MODEL:
    TYPE: MobileViT
    NAME: mobilevit_xxs
    DIMS: [64, 80, 96]
    CHANNELS: [16, 16, 24, 24, 48, 48, 64, 64, 80, 80, 320]
    NUM_CLASSES: 100
    MV2_EXPAANSION: 2