DATA:
    IMAGE_SIZE: 256
    CROP_PCT: 0.875
MODEL:
    TYPE: MobileViT
    NAME: mobilevit_s
    DIMS: [16, 32, 64, 64, 64, 96, 128, 160, 640] # conv3x3 + mobile v2 block output channels
    HIDDEN_DIMS: [144, 192, 240] # mobile vit block hidden dim
